FROM postgres:17

# Install ca-certificates
RUN apt-get update &&  \
    apt-get install -y \
    ca-certificates &&\
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

# Add custom CAs (for Fujitsu SIG)
COPY ./.devcontainer/certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates

RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8

ARG UID
ARG GID

RUN usermod -u ${UID} postgres && groupmod -g ${GID} postgres
RUN chown -R postgres:postgres /var/lib/postgresql /var/run/postgresql /etc/postgresql

USER postgres
