FROM python:3.13-slim

# Install git
RUN apt-get update &&  \
    apt-get install -y \
    ca-certificates \
    postgresql-client \
    git && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

# Set separate working directory for easier debugging.
WORKDIR /app

# Add custom CAs (for Fujitsu SIG)
COPY ./.devcontainer/certificates/* /usr/local/share/ca-certificates/
RUN update-ca-certificates

# Create virtual environment.
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# Install Python Packages. 
RUN pip install --upgrade certifi
COPY /.devcontainer/requirements.txt /tmp/
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Add custom CAs (for Fujitsu SIG) to Python environment.
RUN ls /usr/local/share/ca-certificates/*  | xargs cat >> $(python -m certifi)

# Switch to new working directory as default bind mount location.
WORKDIR /workspace

# Set SQLFluff command for image.
CMD ["bash"]
